### ISSUE TITLE
Formal board page (HTML,CSS,JS)

### ISSUE THREAD

**Issue by RbCream** [Look-Project/look#12]
# Description
Formal 게시판 외형 생성

# To-do
- [ ] 상단메뉴바 적용
- [ ] 컨텐츠 영역 생성
- [ ] 컨텐츠 영역 상단 정렬메뉴 + 글작성 버튼 + 검색창 작성
- [ ] 켄텐츠 영역 게시물 작성

# ETC
무한스크롤 부가기능 적용 예정
