### ISSUE TITLE
Formal [ board list ] Front design

### ISSUE THREAD

**Issue by RbCream** [Look-Project/look#19]
# Description
포멀게시판 게시글 목록 페이지 생성

# To-do
- [ ]  게시글 이미지 목록 + 프로필(사진) + 글 보이게 배치
- [ ]  글작성, 글수정 버튼 생성
- [ ]  글 목록 버튼 생성

# ETC
- [ ]  ++ 무한스크롤 API 도입예정 (Intersection Observer API)
