### ISSUE TITLE
나눔게시판 테이블 및 기본 틀 작업 예정

### ISSUE THREAD

**Issue by ha2way** [Look-Project/look#8]
# Description
나눔게시판의 데이터베이스 테이블 작성 후 연동 및 기본 게시판 틀 작업
# To-do
- [ ] 나눔게시판 테이블 작성
- [ ] 나눔게시판 데이터베이스 연동
- [ ] 기본게시판 틀 작업으로 연동 확인

# ETC
 이미지 게시판의 8분할 틀 만들기의 기본 정보 수집 필요
